services:
  postgres_products:
    image: postgres:16
    restart: always
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  api_products:
    build: .
    depends_on:
      - products_db
    ports:
      - "4001:4001"

    stdin_open: true
    tty: true
    env_file: .env
