services:
  postgres_products:
    image: postgres:16
    restart: always
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api_products:
    depends_on:
      - postgres_products
    build: .
    env_file: ./.env
    ports:
      - "4000:4000"

    stdin_open: true
    tty: true
volumes:
  postgres:
